### ISSUE TITLE
UNICODE related exception in file name parsing causes crash

### ISSUE THREAD

**Issue by hdb3** [alberthier/sweech-cli#1]
stack trace attached, and screen grab of the web GUI open on the same device directory.
It looks like it is some kind of quote character in the file name  - when i down load on my Linux system the filename is: 'SHE%u2019S ELECTRIC PART 1.enc'

[Screenshot from 2019-05-01 11-13-03] (https://user-images.githubusercontent.com/4218547/57013297-ca395480-6c02-11e9-9585-7102aec64aaf.png)
[stacktrace.txt] (https://github.com/alberthier/sweech-cli/files/3134234/stacktrace.txt)

**Comment by alberthier** [comment]
Indeed, unicode characters encoding seems to be broken with python2's `quote` function

As a short term workaround, you can try to run the script with python3
Just replace `#!/usr/bin/env python` at the beginning of the file with `#!/usr/bin/env python3`

Thanks for the feedback

**Comment by hdb3** [comment]
I'm sure you've nailed it looking at the patch, but I'll check anyway.  I worked around it by deleting the files! So not trivial to recreate (but there were several such files including one created on the phone by Revolut.!)
BTW  congrats on building such a fine app without a big corporation behind you.  I wish you well.
